### PR TITLE
Two prediction options and debug code

### PR DESCRIPTION
**Pull request by davidbejarcaceres**
- Added option to activate prediction using 50-50 criteria after passing argument -P False, by default True uses the improved prediction described in the equation.

- Adds code to debug mode.

### CODE REVIEW

**Comment by vicente-gonzalez-ruiz** [comment]
The code is right, but please, remove the temporal `.pyc` files from your repo.

**Comment by davidbejarcaceres** [comment]
Done removing cache .pyc files

**Comment by vicente-gonzalez-ruiz** [comment]
OK, "sounds" good but:

1. Remove `.vscode/settings.json`.
2. There are still `.pyc` files.
3. I prefer that the conditional code to be included by using the import directive. See the slack channel. Besides, a structure `if a=True: ... if a=False: ...` does not make sense. Use `if a: ... else: ...`.

**Comment by vicente-gonzalez-ruiz** [comment]
OK, I close this PR only for following the _protocol_. If your group is selected, I'll request you to resend the PR.

**Pull request closed without merging**
